# Generated by Django 4.2.5 on 2024-01-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='midea/home/')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problems_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('images', models.ImageField(upload_to='midea/solutions/')),
            ],
        ),
        migrations.CreateModel(
            name='Problems_right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('images', models.ImageField(upload_to='midea/solutions/')),
            ],
        ),
        migrations.CreateModel(
            name='Social_Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='midea/social_networks/networks/')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Networks_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.CharField(max_length=250)),
                ('telegram_link', models.CharField(max_length=250)),
                ('telegram_bot', models.CharField(max_length=250)),
                ('forkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.social_networks')),
            ],
        ),
    ]
