# Generated by Django 4.2.5 on 2024-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('funksiya_update_right', models.CharField(max_length=150)),
                ('funksiya_update_left', models.CharField(max_length=150)),
            ],
        ),
    ]
